// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZd9P53qFx1VkaJX9gnUqVIOTA8yvlHaM',
    appId: '1:105969995275:web:819862a83186f55c35410e',
    messagingSenderId: '105969995275',
    projectId: 'rankit-web-df73a',
    authDomain: 'rankit-web-df73a.firebaseapp.com',
    storageBucket: 'rankit-web-df73a.firebasestorage.app',
    measurementId: 'G-9TDSC65565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZAfmEoB8tL5RlxEDBw7N8wiTol2v9uWU',
    appId: '1:105969995275:android:70c74803d4903cac35410e',
    messagingSenderId: '105969995275',
    projectId: 'rankit-web-df73a',
    storageBucket: 'rankit-web-df73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jKfTsaj-oHAOqPA06Kjl3vWTkwXW_WA',
    appId: '1:105969995275:ios:2f1b29ad5c78f35b35410e',
    messagingSenderId: '105969995275',
    projectId: 'rankit-web-df73a',
    storageBucket: 'rankit-web-df73a.firebasestorage.app',
    iosBundleId: 'com.rankerating.rankerating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_jKfTsaj-oHAOqPA06Kjl3vWTkwXW_WA',
    appId: '1:105969995275:ios:2f1b29ad5c78f35b35410e',
    messagingSenderId: '105969995275',
    projectId: 'rankit-web-df73a',
    storageBucket: 'rankit-web-df73a.firebasestorage.app',
    iosBundleId: 'com.rankerating.rankerating',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZd9P53qFx1VkaJX9gnUqVIOTA8yvlHaM',
    appId: '1:105969995275:web:bf9bc57591ba181e35410e',
    messagingSenderId: '105969995275',
    projectId: 'rankit-web-df73a',
    authDomain: 'rankit-web-df73a.firebaseapp.com',
    storageBucket: 'rankit-web-df73a.firebasestorage.app',
    measurementId: 'G-M99289247H',
  );
}
